### ISSUE TITLE
IntelliJ import，There is conflict between java version for gradle build and project

### ISSUE THREAD

**Issue by jimchen1009** [collinsmith/riiablo#146]
Java 11：
A problem occurred evaluating project ':android'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

But Java 11， The method change the first int parameter to long。
 regOpenKey = userClass.getDeclaredMethod(
          "WindowsRegOpenKey", new Class[]{int.class, byte[].class, int.class}
      );

**Comment by collinsmith** [comment]
Seems this was an API change in Java 11+, not sure how to resolve it yet
https://stackoverflow.com/a/65943011/3134241 
![image](https://user-images.githubusercontent.com/4914327/156232087-21640ca1-b3b5-4cac-b446-8d05013ff9a8.png)

**Comment by collinsmith** [comment]
Fixed by 4eba03fc1c63dd76759a385a642dd484852bde9e
