### ISSUE TITLE
Make compiled builds of projet

### ISSUE THREAD

**Issue by JunioJsv** [collinsmith/riiablo#47]
Where can I get the apk file? without having to compile everything

**Comment by collinsmith** [comment]
You're welcome to try this. There are still some hoops to jump through and optimizations to be made, so I don't suggest it yet. You'll need to copy your MPQs into `\Android\data\com.riiablo\files` once the APK is installed. The client will then unpack the audio files when you run it the first time. Uninstalling the APK will delete this folder. You will need ~3.5GB for the MPQs and the unpacked audio files. Save files (d2s) should be copied into `...\com.riiablo\files\Save`
[android-debug.zip](https://github.com/collinsmith/riiablo/files/3082690/android-debug.zip)

**Comment by JunioJsv** [comment]
Android 8.1, Armv7 32bits :/
[](https://i.ibb.co/jHL019R/Screenshot-2019-04-16-12-34-39.png)

**Comment by JunioJsv** [comment]
Android 8.1, armv7 32bits [https://i.ibb.co/jHL019R/Screenshot-2019-04-16-12-34-39.png](url)

**Comment by JunioJsv** [comment]
Android 8.1, armv7 32bits [](https://i.ibb.co/jHL019R/Screenshot-2019-04-16-12-34-39.png)

**Comment by collinsmith** [comment]
Unzip it first? English please. My device is 7.0 and I think it should work with quite a bit lower.

**Comment by JunioJsv** [comment]
of course I unpacked, I installed the app but when I try to open it, aparace the error, unfortunately "riiablo" stopped working

**Comment by collinsmith** [comment]
I can't help you without a stack trace, so I guess you'll have to wait. Just double check and make sure you copied the MPQs into the correct directory on your device is all I can suggest. Installing the APK should create the directory, but you still need to copy them from your PC.
