### ISSUE TITLE
Guide of how to compile this project and eviorment settings 

### ISSUE THREAD

**Issue by lomatus** [collinsmith/riiablo#60]
I'm a d2 funs and exited to see this project and thanks for your selfless work.
I have try to  complie this project wihout success, the problem are all related to LibGDX eviorment.
Could you provide a guide document for beginner please.

**Comment by liberodark** [comment]
Yes is not same for me but no have see how to compile on linux

**Comment by SomeFire** [comment]
I use IDEA, and it runs `DesktopLauncher` successfully on 113d765d commit.

**Comment by collinsmith** [comment]
Duplicate of #6
